Refactor commands

diff --git a/bin/ask-msg b/bin/ask-msg
--- a/bin/ask-msg
+++ b/bin/ask-msg
@@ -1,12 +1,13 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} MESSAGE [TITLE]
+
+Request a user action."
 
 set -e
-
-[ "$1" = '--help' ] &&
-echo "Usage: ${0##*/} MESSAGE [TITLE]
-
-Request a user action." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
-
-osascript -e "tell app \"System Events\" to display dialog \"$1\" with title \"${2-Notification}\"" > /dev/null 2>&1
+case "$1" in
+(-h|--help) echo "$USAGE" ;;
+('') echo "${0##*/}: MESSAGE missing" >&2 && exit 1 ;;
+(*)
+  osascript -e "tell app \"System Events\" to display dialog \"$1\" with title \"${2-Notification}\"" >/dev/null 2>&1
+;;
+esac
diff --git a/bin/assemble-slide b/bin/assemble-slide
--- a/bin/assemble-slide
+++ b/bin/assemble-slide
@@ -1,29 +1,35 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} [-d|--draft] SOURCE ...
+
+Assemble reveal.js slide from SOURCE."
 
 set -e
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} [-d|--draft] SOURCE ...
-
-Assemble reveal.js slide from SOURCE." && exit
-
 die() {
-  (>&2 echo "${0##*/}: $1")
+  echo "${0##*/}: $1" >&2
   exit 1
 }
 
-if [ "$1" = "-d" ] || [ "$1" = "--draft" ]
-then
-  shift
+case "$1" in
+(-d|--draft)
   ARGS=""
-else
-  ARGS="--embed-resources"
-fi
-[ $# = 0 ] && die 'SOURCE name missing'
-(command -v pandoc >/dev/null 2>&1) || die 'pandoc not installed'
+  shift
+;;
+(-h|--help) echo "$USAGE" && exit ;;
+('') die "SOURCE missing" ;;
+(*) ARGS="--embed-resources" ;;
+esac
+
+command -v pandoc >/dev/null 2>&1 || die 'pandoc not installed'
 [ -d "$HOME/.local/share/pandoc/reveal" ] || die 'reveal not installed'
 
 for SOURCE in "$@"
 do
   [ -f "$SOURCE" ] || die "file not found - $SOURCE"
-  pandoc -t revealjs  -s "$SOURCE" -o "${SOURCE%.*}.html" -V revealjs-url:"$HOME/.local/share/pandoc/reveal" "$ARGS"
+  pandoc \
+    -t revealjs  \
+    -s "$SOURCE" \
+    -o "${SOURCE%.*}.html" \
+    -V revealjs-url:"$HOME/.local/share/pandoc/reveal" \
+    "$ARGS"
 done
diff --git a/bin/clean-brew b/bin/clean-brew
--- a/bin/clean-brew
+++ b/bin/clean-brew
@@ -1,10 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Clean up Homebrew stuff."
 
-Clean up Homebrew stuff." && exit
-
-brew upgrade
-brew cleanup -s
-# rm -rfv "$(brew --cache)" >/dev/null
-brew tap --repair
+set -e
+case "$1" in
+('')
+  brew upgrade
+  brew cleanup -s
+  # rm -rfv "$(brew --cache)" >/dev/null
+  brew tap --repair
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-caches b/bin/clean-caches
--- a/bin/clean-caches
+++ b/bin/clean-caches
@@ -1,12 +1,18 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Clean all library caches. (May require password.)"
 
-Clean all library caches. (May require password.)" && exit
-
-sudo rm -rfv /Library/Caches/* >/dev/null
-sudo rm -rfv /System/Library/Caches/* >/dev/null
-sudo rm -rfv /private/var/folders/bh/*/*/*/* >/dev/null
-rm -rfv "$HOME/Library/Caches/*" >/dev/null
-rm -rfv "$HOME/.cache" >/dev/null
-[ "$PYENV_VIRTUALENV_CACHE_PATH" ] && rm -rfv "$PYENV_VIRTUALENV_CACHE_PATH" >/dev/null
+set -e
+case "$1" in
+('')
+  sudo rm -rfv /Library/Caches/* >/dev/null
+  sudo rm -rfv /System/Library/Caches/* >/dev/null
+  sudo rm -rfv /private/var/folders/bh/*/*/*/* >/dev/null
+  rm -rfv "$HOME/Library/Caches/*" >/dev/null
+  rm -rfv "$HOME/.cache" >/dev/null
+  [ "$PYENV_VIRTUALENV_CACHE_PATH" ] && rm -rfv "$PYENV_VIRTUALENV_CACHE_PATH" >/dev/null
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-docker b/bin/clean-docker
--- a/bin/clean-docker
+++ b/bin/clean-docker
@@ -1,12 +1,18 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Clean up Docker stuff."
 
-Clean up Docker stuff." && exit
-
-start-docker
-docker image prune -f
-docker container prune -f
-docker volume prune -f
-docker network prune -f
-docker system prune -f -a
+set -e
+case "$1" in
+('')
+  start-docker
+  docker image prune -f
+  docker container prune -f
+  docker volume prune -f
+  docker network prune -f
+  docker system prune -f -a
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-gems b/bin/clean-gems
--- a/bin/clean-gems
+++ b/bin/clean-gems
@@ -1,16 +1,15 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} [-a|--all]
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} [--all]
+Clean up Ruby gems. Option '--all' removes all installed gems."
 
-Clean up Ruby gems. Option '--all' removes all installed gems." && exit
-
+set -e
 with_rbenv() {
   for ruby in $(rbenv versions --bare); do
     echo ":: Ruby $ruby"
     RBENV_VERSION="$ruby" rbenv exec $@
   done
 }
-
 with_asdf() {
 	for ruby in $(asdf list ruby); do
     ruby="${ruby#\*}"
@@ -18,8 +17,15 @@ with_asdf() {
     ASDF_RUBY_VERSION="$ruby" asdf exec $@
 	done
 }
-
-CMD='gem cleanup'
-[ "$1" = "--all" ] && CMD='gem uninstall -aIx'
-type 'rbenv' >/dev/null 2>&1 && with_rbenv "$CMD"
-type 'asdf' >/dev/null 2>&1 && with_asdf "$CMD"
+case "$1" in
+('')
+  type 'rbenv' >/dev/null 2>&1 && with_rbenv gem cleanup
+  type 'asdf' >/dev/null 2>&1 && with_asdf gem cleanup
+;;
+(-a|--all)
+  type 'rbenv' >/dev/null 2>&1 && with_rbenv gem uninstall -aIx
+  type 'asdf' >/dev/null 2>&1 && with_asdf gem uninstall -aIx
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-npm b/bin/clean-npm
--- a/bin/clean-npm
+++ b/bin/clean-npm
@@ -1,7 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Clean up NPM cache."
 
-Clean up NPM cache." && exit
-
-npm cache clean --force
+set -e
+case "$1" in
+('') npm cache clean --force ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-system b/bin/clean-system
--- a/bin/clean-system
+++ b/bin/clean-system
@@ -1,31 +1,35 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Clean system. (May require password.)"
 
 set -e
+case "$1" in
+('')
+	echo '❗️ clean all stuff'
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+	cleanup() {
+		trap - INT TERM EXIT
+	}
+	trap cleanup INT TERM EXIT
 
-Clean system. (May require password.)" && exit
+	while true; do
+		sudo -n true
+		sleep 60
+		kill -0 "$$" || exit
+	done 2>/dev/null &
 
-echo '❗️ clean all stuff'
+	(command -v brew >/dev/null 2>&1) && echo '🗑️ clean brew stuff...' && clean-brew
+	(command -v docker >/dev/null 2>&1) && echo '🗑️ clean Docker...' && clean-docker
+	(command -v npm >/dev/null 2>&1) && echo '🗑️ clean NPM...' && clean-npm
+	(command -v yarn >/dev/null 2>&1) && echo '🗑️ clean Yarn...' && clean-yarn
+	(command -v gem >/dev/null 2>&1) && echo '🗑️ clean gems...' && clean-gems
 
-cleanup() {
-  trap - INT TERM EXIT
-}
-trap cleanup INT TERM EXIT
-
-while true; do
-	sudo -n true
-	sleep 60
-	kill -0 "$$" || exit
-done 2>/dev/null &
-
-(command -v brew >/dev/null 2>&1) && echo '🗑️ clean brew stuff...' && clean-brew
-(command -v docker >/dev/null 2>&1) && echo '🗑️ clean Docker...' && clean-docker
-(command -v npm >/dev/null 2>&1) && echo '🗑️ clean NPM...' && clean-npm
-(command -v yarn >/dev/null 2>&1) && echo '🗑️ clean Yarn...' && clean-yarn
-(command -v gem >/dev/null 2>&1) && echo '🗑️ clean gems...' && clean-gems
-
-echo '🗑️ remove system log files...' && clean-logs
-echo '🗑️ clean all library caches...' && clean-caches
-echo '🗑️ cleanup XCode derived data and archives...' && clean-xcode
-echo '🗑️ clean Trashes...' && clean-trashes
+	echo '🗑️ remove system log files...' && clean-logs
+	echo '🗑️ clean all library caches...' && clean-caches
+	echo '🗑️ cleanup XCode derived data and archives...' && clean-xcode
+	echo '🗑️ clean Trashes...' && clean-trashes
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-trashes b/bin/clean-trashes
--- a/bin/clean-trashes
+++ b/bin/clean-trashes
@@ -1,8 +1,14 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Clean all trashes. (May require password.)"
 
-Clean all trashes. (May require password.)" && exit
-
-sudo rm -rfv /Volumes/*/.Trashes/* >/dev/null
-rm -rfv ~/.Trash/* >/dev/null
+set -e
+case "$1" in
+('')
+  sudo rm -rfv /Volumes/*/.Trashes/* >/dev/null
+  rm -rfv ~/.Trash/* >/dev/null
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clean-xcode b/bin/clean-xcode
--- a/bin/clean-xcode
+++ b/bin/clean-xcode
@@ -1,9 +1,15 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Cleanup XCode derived data and archives."
 
-Cleanup XCode derived data and archives." && exit
-
-rm -rfv ~/Library/Developer/Xcode/DerivedData/* >/dev/null
-rm -rfv ~/Library/Developer/Xcode/Archives/* >/dev/null
-rm -rfv ~/Library/Developer/Xcode/iOS Device Logs/* >/dev/null
+set -e
+case "$1" in
+('')
+  rm -rfv ~/Library/Developer/Xcode/DerivedData/* >/dev/null
+  rm -rfv ~/Library/Developer/Xcode/Archives/* >/dev/null
+  rm -rfv ~/Library/Developer/Xcode/iOS Device Logs/* >/dev/null
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/clear-dns-cache b/bin/clear-dns-cache
--- a/bin/clear-dns-cache
+++ b/bin/clear-dns-cache
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Clear the DNS cache. (May require password.)"
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Clear the DNS cache. (May require password.)" && exit
-
-sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
+case "$1" in
+('') sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/compare-disk-id b/bin/compare-disk-id
--- a/bin/compare-disk-id
+++ b/bin/compare-disk-id
@@ -1,19 +1,22 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} NAME
 
-set -e
-
-[ "$1" = '--help' ]  && echo "Usage: ${0##*/} NAME
-
-Checks if disk NAME is the correct one." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: NAME missing") && exit 1
+Checks if disk NAME is the correct one."
 
 # check partition UUID against regsitered id (stored in pass)
-if [ "$(print-disk-uuid "$1")" = "$(print-system-secret "$1")" ]
-then
-   # test if really mounted
-   if [ -f "/Volumes/$1/.fseventsd/fseventsd-uuid" ]
-   then exit 0
+
+set -e
+case "$1" in
+('') echo "${0##*/}: NAME missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+   if [ "$(print-disk-uuid "$1")" = "$(print-system-secret "$1")" ]
+   then
+      # test if really mounted
+      if [ -f "/Volumes/$1/.fseventsd/fseventsd-uuid" ]
+      then exit 0
+      fi
    fi
-fi
-exit 1
+   exit 1
+;;
+esac
diff --git a/bin/convert-html-markdown b/bin/convert-html-markdown
--- a/bin/convert-html-markdown
+++ b/bin/convert-html-markdown
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert HTML from stdin into MARKDOWN to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert HTML from stdin into MARKDOWN to stdout." && exit
-
-pandoc --from=html --to=gfm "$@"
+case "$1" in
+('') pandoc --from=html --to=gfm "$@" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-html-text b/bin/convert-html-text
--- a/bin/convert-html-text
+++ b/bin/convert-html-text
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert HTML from stdin into plain TEXT to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert HTML from stdin into plain TEXT to stdout." && exit
-
-pandoc --from=html --to=plain "$@"
+case "$1" in
+('') pandoc --from=html --to=plain "$@" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-json-yaml b/bin/convert-json-yaml
--- a/bin/convert-json-yaml
+++ b/bin/convert-json-yaml
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert JSON from stdin into YAML to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert JSON from stdin into YAML to stdout." && exit
-
-ruby --disable-all -rpsych -roj -e'Psych.dump Oj.load(STDIN),STDOUT'
+case "$1" in
+('') ruby --disable-all -rpsych -roj -e'Psych.dump Oj.load(STDIN),STDOUT' ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-markdown-html b/bin/convert-markdown-html
--- a/bin/convert-markdown-html
+++ b/bin/convert-markdown-html
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert MARKDOWN from stdin into HTML to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert MARKDOWN from stdin into HTML to stdout." && exit
-
-pandoc --from=gfm --to=html5 "$@"
+case "$1" in
+('') pandoc --from=gfm --to=html5 "$@" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-markdown-pdf b/bin/convert-markdown-pdf
--- a/bin/convert-markdown-pdf
+++ b/bin/convert-markdown-pdf
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert MARKDOWN from stdin into PDF to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert MARKDOWN from stdin into PDF to stdout." && exit
-
-pandoc --from=gfm --to=pdf "$@"
+case "$1" in
+('') pandoc --from=gfm --to=pdf "$@" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-mp4-m4r b/bin/convert-mp4-m4r
--- a/bin/convert-mp4-m4r
+++ b/bin/convert-mp4-m4r
@@ -1,15 +1,17 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} FILE
+
+Convert MP3 ausio FILE to ringtome M4R."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} FILE
-
-Convert MP3 ausio FILE to ringtome M4R." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: FILE missing") && exit 1
-
-for file in "$@"
-do
-	file="${file%.*}"
-	afconvert "$file.mp3" "$file.m4r" -f m4af
-done
+case "$1" in
+('') echo "${0##*/}: FILE missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+	for file in "$@"
+	do
+		file="${file%.*}"
+		afconvert "$file.mp3" "$file.m4r" -f m4af
+	done
+;;
+esac
diff --git a/bin/convert-text-uri b/bin/convert-text-uri
--- a/bin/convert-text-uri
+++ b/bin/convert-text-uri
@@ -1,9 +1,15 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert TEXT from stdin into URI (WWW form component) to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert TEXT from stdin into URI (WWW form component) to stdout." && exit
-
-ruby --disable-all -ruri -e'puts URI.encode_www_form_component STDIN.readlines(chomp:true).join'
+case "$1" in
+('') ruby \
+  --disable-all \
+  -ruri \
+  -e'puts URI.encode_www_form_component STDIN.readlines(chomp:true).join'
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/convert-yaml-json b/bin/convert-yaml-json
--- a/bin/convert-yaml-json
+++ b/bin/convert-yaml-json
@@ -1,9 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Convert YAML from stdin into JSON to stdout."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Convert YAML from stdin into JSON to stdout." && exit
-
-ruby --disable-all -rpsych -roj -e'Oj.to_stream STDOUT,Psych.load_stream(STDIN)'
+case "$1" in
+('') ruby \
+  --disable-all \
+  -rpsych \
+  -roj \
+  -e'Oj.to_stream STDOUT,Psych.load_stream(STDIN)'
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/create-disk-image b/bin/create-disk-image
--- a/bin/create-disk-image
+++ b/bin/create-disk-image
@@ -1,21 +1,22 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} [--encrypt] DIR [NAME]
+
+Create disk image from DIR named NAME, optionally encrypted."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} [--encrypt] DIR [NAME]
-
-Create disk image from DIR named NAME, optionally encrypted." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: DIR missing") && exit 1
-
 OPTIONS="-nospotlight -noanyowners"
 TYPE=volume
-if [ "$1" = "--encrypt" ] || [ "$1" = "-e" ]
-then
+case "$1" in
+(-e|--encrypt)
   TYPE="encrypted volume"
   OPTIONS="-encryption AES-256 -stdinpass $OPTIONS"
   shift
-fi
+;;
+(-h|--help) echo "$USAGE" && exit ;;
+('') echo "${0##*/}: DIR missing " >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
+
 DIR=$(cd "$1";pwd)
 readonly BASENAME="${DIR##*/}"
 OPTIONS="-srcfolder \"$DIR\" -ov \"./$BASENAME.dmg\" $OPTIONS"
diff --git a/bin/download-audio b/bin/download-audio
--- a/bin/download-audio
+++ b/bin/download-audio
@@ -1,20 +1,23 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} URL
+
+Download a audio or playlist as MP3 from given URL to '$HOME/Downloads'."
 
 set -e
-readonly TDIR="$HOME/Downloads"
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
-
-Download a audio or playlist as MP3 from given URL to '$TDIR'." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
-
-mkdir -p "$TDIR"
-cd "$TDIR"
-yt-dlp \
-    --extract-audio --audio-format m4a --audio-quality 0 \
-    --embed-metadata \
-    --embed-thumbnail \
-    --concurrent-fragments 8 \
-    --geo-bypass \
-    "$@"
+case "$1" in
+('') echo "${0##*/}: URL missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+    mkdir -p "$HOME/Downloads"
+    cd "$HOME/Downloads"
+    yt-dlp \
+        --extract-audio --audio-format m4a --audio-quality 0 \
+        --embed-metadata \
+        --embed-thumbnail \
+        --no-overwrites \
+        --console-title \
+        --concurrent-fragments 8 \
+        --geo-bypass \
+        "$@"
+;;
+esac
diff --git a/bin/download-file b/bin/download-file
--- a/bin/download-file
+++ b/bin/download-file
@@ -1,14 +1,21 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} URL
+
+Download a file from given URL to '$HOME/Downloads'."
 
 set -e
-readonly TDIR="$HOME/Downloads"
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
-
-Download a file from given URL to '$TDIR'." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
-
-mkdir -p "$TDIR"
-cd "$TDIR"
-curl -sLNO "$@"
+case "$1" in
+('') echo "${0##*/}: URL missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) curl \
+  --output-dir "$HOME/Downloads" \
+  --create-dirs  \
+  --remote-name \
+  --fail \
+  --compressed \
+  --remove-on-error \
+  --progress-bar \
+  --location \
+  "$@"
+;;
+esac
diff --git a/bin/download-video b/bin/download-video
--- a/bin/download-video
+++ b/bin/download-video
@@ -1,17 +1,20 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} URL
+
+Download a video or video playlist from given URL to '$HOME/Downloads'."
 
 set -e
-readonly TDIR="$HOME/Downloads"
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
-
-Download a video or video playlist from given URL to '$TDIR'." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
-
-mkdir -p "$TDIR"
-cd "$TDIR"
-yt-dlp \
-    --concurrent-fragments 8 \
-    --geo-bypass \
-    "$@"
+case "$1" in
+('') echo "${0##*/}: URL missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+    mkdir -p "$HOME/Downloads"
+    cd "$HOME/Downloads"
+    yt-dlp \
+        --no-overwrites \
+        --console-title \
+        --concurrent-fragments 8 \
+        --geo-bypass \
+        "$@"
+;;
+esac
diff --git a/bin/each-ruby b/bin/each-ruby
--- a/bin/each-ruby
+++ b/bin/each-ruby
@@ -1,12 +1,17 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} COMMAND
+
+Execute given command for each installed ruby version."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Execute given command for each installed ruby version." && exit
-
-for ruby in $(asdf list ruby | grep -oE '[0-9]+\.[0-9]+\.[0-9]+'); do
-	echo "• Ruby $ruby"
-	ASDF_RUBY_VERSION="$ruby" asdf exec $@
-done
+case "$1" in
+('') echo "${0##*/}: COMMAND missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+	for ruby in $(asdf list ruby | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+	do
+		echo "• Ruby $ruby"
+		ASDF_RUBY_VERSION="$ruby" asdf exec $@
+	done
+;;
+esac
diff --git a/bin/edit-text b/bin/edit-text
--- a/bin/edit-text
+++ b/bin/edit-text
@@ -1,16 +1,18 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} [FILE | NAME]
+
+Edit given FILE or project NAME."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} [FILE | NAME]
-
-Edit given FILE or project NAME." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: FILE | NAME missing") && exit 1
-
-if [ -e "$1" ]
-then code "$1"
-else
-  PROJECT="$(list-projects "$1")" || (>&2 echo "${0##*/}: no such project - $1" && exit 2)
-  code "$PROJECT"
-fi
+case "$1" in
+('') echo "${0##*/}: FILE or NAME missing " >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  if [ -r "$1" ]
+  then code "$1"
+  else
+    PROJECT="$(list-projects "$1")" || (>&2 echo "${0##*/}: no such project - $1" && exit 2)
+    code "$PROJECT"
+  fi
+;;
+esac
diff --git a/bin/eject-disks b/bin/eject-disks
--- a/bin/eject-disks
+++ b/bin/eject-disks
@@ -1,9 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Ejects all removeable disks."
 
 set -e
+case "$1" in
+('')
+  osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
 
-Ejects all removeable disks." && exit
 
-osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
diff --git a/bin/fetch-web b/bin/fetch-web
--- a/bin/fetch-web
+++ b/bin/fetch-web
@@ -1,11 +1,17 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} URL
+
+Display a file from given URL."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
-
-Display a file from given URL." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
-
-curl -sLN $@
+case "$1" in
+('') echo "${0##*/}: URL missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) curl \
+  --fail \
+  --compressed \
+  --silent \
+  --location \
+  "$@"
+;;
+esac
diff --git a/bin/flush-routes b/bin/flush-routes
--- a/bin/flush-routes
+++ b/bin/flush-routes
@@ -1,11 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} INTERFACE
+
+Flush routes for your INTERFACE (like en0, en1, ...). (May require password.)"
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} INTERFACE
-
-Flush routes for your INTERFACE (like en0, en1, ...). (May require password.)" && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: name of INTERFACE missing") && exit 1
-
-sudo ifconfig "$1" down && sudo route flush && sudo ifconfig "$1" up
+case "$1" in
+('') echo "${0##*/}: INTERFACE name missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) sudo ifconfig "$1" down && sudo route flush && sudo ifconfig "$1" up ;;
+esac
diff --git a/bin/list-applications b/bin/list-applications
--- a/bin/list-applications
+++ b/bin/list-applications
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+List downloaded apps from AppStore."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List downloaded apps from AppStore." && exit
-
-mdfind kMDItemAppStoreHasReceipt=1
+case "$1" in
+('') mdfind kMDItemAppStoreHasReceipt=1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/list-disk-status b/bin/list-disk-status
--- a/bin/list-disk-status
+++ b/bin/list-disk-status
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+List information about all disks."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List information about all disks." && exit
-
-diskutil list
+case "$1" in
+('') diskutil list ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/list-display-info b/bin/list-display-info
--- a/bin/list-display-info
+++ b/bin/list-display-info
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+List informatin about the display."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List informatin about the display." && exit
-
-system_profiler SPDisplaysDataType
+case "$1" in
+('') system_profiler SPDisplaysDataType ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/list-ports b/bin/list-ports
--- a/bin/list-ports
+++ b/bin/list-ports
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+List all opened ports and related processes."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List all opened ports and related processes." && exit
-
-lsof -i -P | grep LISTEN
+case "$1" in
+('') lsof -i -P | grep LISTEN ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/list-whois b/bin/list-whois
--- a/bin/list-whois
+++ b/bin/list-whois
@@ -1,14 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} URL
+
+Display WHOIS rrecord about given URL or domain."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
-
-Display WHOIS rrecord about given URL or domain." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
-
-domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
-[ -z "$domain" ] && domain=$1
-echo "whois record for $domain:"
-/usr/bin/whois -h whois.internic.net "$domain" | sed '/NOTICE:/q'
+case "$1" in
+('') echo "${0##*/}: NAME missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
+  [ -z "$domain" ] && domain=$1
+  echo "whois record for $domain:"
+  /usr/bin/whois -h whois.internic.net "$domain" | sed '/NOTICE:/q'
+;;
+esac
diff --git a/bin/list-wlan-status b/bin/list-wlan-status
--- a/bin/list-wlan-status
+++ b/bin/list-wlan-status
@@ -1,9 +1,10 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-set -e
+List information about current WLAN connection."
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List information about current WLAN connection." && exit
-
-/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I
+case "$1" in
+('') /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/list-wlans b/bin/list-wlans
--- a/bin/list-wlans
+++ b/bin/list-wlans
@@ -1,9 +1,10 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-set -e
+List WLAN information."
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-List WLAN information." && exit
-
-/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s
+case "$1" in
+('') /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/open-search b/bin/open-search
--- a/bin/open-search
+++ b/bin/open-search
@@ -1,13 +1,15 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} ENGINE TERM
+
+Open search ENGINE with TERM."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} <ENGINE> TERM
-
-Open search ENGINE with TERM." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: OPTION missing") && exit 1
-[ $# -lt 2 ] && (>&2 echo "${0##*/}: TERM missing") && exit 1
-
-url="$(print-search-url "$@")" || exit $?
-open "$url"
+case "$1" in
+('') echo "${0##*/}: argument missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  [ $# -lt 2 ] && echo "${0##*/}: TERM missing" >&2 && exit 1
+  url="$(print-search-url "$@")" || exit $?
+  open "$url"
+;;
+esac
diff --git a/bin/play-audio b/bin/play-audio
--- a/bin/play-audio
+++ b/bin/play-audio
@@ -1,11 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} FILE
+
+Plays given audio FILE."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} FILE
-
-Plays given audio FILE." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: FILE missing") && exit 1
-
-afplay -q 1 $@
+case "$1" in
+('') echo "${0##*/}: FILE missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) afplay -q 1 "$@" ;;
+esac
diff --git a/bin/print-battery-status b/bin/print-battery-status
--- a/bin/print-battery-status
+++ b/bin/print-battery-status
@@ -1,10 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Print the battery load state (in percent)."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Print the battery load state (in percent)." && exit
-
-pmset -g batt | sed -nE 's/^.*[^0-9]([0-9]+\%);.*$/\1/p'
-
+case "$1" in
+('') pmset -g batt | sed -nE 's/^.*[^0-9]([0-9]+\%);.*$/\1/p' ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/print-ip b/bin/print-ip
--- a/bin/print-ip
+++ b/bin/print-ip
@@ -1,21 +1,18 @@
 #! /bin/sh
-
-set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+USAGE="Usage: ${0##*/}
 
 Print external or local IP address.
 
 options:
    -4, --ipv4   show IPv4 address (default)
    -6, --ipv6   show IPv6 address
-   -l, --local  show local address" && exit
+   -l, --local  show local address"
 
-if [ "$1" =  '-4' ] || [ "$1" =  '--ipv4' ] || [ "$1" =  '' ]
-then curl https://ipecho.net/plain && echo
-elif [ "$1" =  '-6' ] || [ "$1" =  '--ipv6' ]
-then dig @resolver1.opendns.com ANY myip.opendns.com +short
-elif [ "$1" =  '-l' ] || [ "$1" =  '--local' ]
-then ipconfig getifaddr en0
-else (>&2 echo "${0##*/}: unknown option '$1'") && exit 1
-fi
+set -e
+case "$1" in
+(-4|--ipv4|'') curl https://ipecho.net/plain && echo ;;
+(-6|--ipv6) dig @resolver1.opendns.com ANY myip.opendns.com +short ;;
+(-1|--local) ipconfig getifaddr en0 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/print-search-url b/bin/print-search-url
--- a/bin/print-search-url
+++ b/bin/print-search-url
@@ -1,8 +1,5 @@
 #! /bin/sh
-
-set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} <OPTION> [TERM]
+USAGE="Usage: ${0##*/} OPTION [TERM]
 
 Print search URL.
 
@@ -15,39 +12,21 @@ Options:
    -p, --perplexity   print Perplexity search URL
    -v, --video        print video search URL (YouTube)
    -w, --wiki         print Wikipedia search URL
-   -y, --youtube      print YouTube search URL" && exit
+   -y, --youtube      print YouTube search URL"
 
-[ $# = 0 ] && (>&2 echo "${0##*/}: OPTION missing") && exit 1
-
+set -e
 case "$1" in
-(-a|--alpha)
-  url='https://www.wolframalpha.com/input/?i='
-  ;;
-(-d|--dict)
-  url='https://pocket.dict.cc/?s='
-  ;;
-(-g|--google)
-  url='https://www.google.de/search?hl=de&as_qdr=all&as_occt=any&num=100&as_q='
-  ;;
-(-h|--github)
-  url='https://github.com/search?q='
-  ;;
-(-i|--image)
-  url='https://www.google.de/search?source=lnms&tbm=isch&sa=X&ei=qWBvVcrKMYWAUa3BgZAF&ved=0CAgQ_AUoAg&biw=1075&bih=728&q='
-  ;;
-(-p|--perplexity)
-  url='https://www.perplexity.ai/search?q='
-  ;;
-(-v|--video|-y|--youtube)
-  url='https://www.youtube.com/results?search_query='
-  ;;
-(-w|--wiki|--wikipedia)
-  url='https://de.wikipedia.org/w/index.php?fulltext=1&search='
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknonw option - $1") && exit 1
-  ;;
+(-a|--alpha) url='https://www.wolframalpha.com/input/?i=' ;;
+(-d|--dict) url='https://pocket.dict.cc/?s=' ;;
+(-g|--google) url='https://www.google.de/search?hl=de&as_qdr=all&as_occt=any&num=100&as_q=' ;;
+(-h|--github) url='https://github.com/search?q=' ;;
+(-i|--image) url='https://www.google.de/search?source=lnms&tbm=isch&sa=X&ei=qWBvVcrKMYWAUa3BgZAF&ved=0CAgQ_AUoAg&biw=1075&bih=728&q=' ;;
+(-p|--perplexity) url='https://www.perplexity.ai/search?q=' ;;
+(-v|--video|-y|--youtube) url='https://www.youtube.com/results?search_query=' ;;
+(-w|--wiki|--wikipedia) url='https://de.wikipedia.org/w/index.php?fulltext=1&search=' ;;
+(--help) echo "$USAGE" && exit ;;
+('') echo "${0##*/}: argument missing" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
-
 shift
 echo "$url$(echo "$@" | convert-text-uri)"
diff --git a/bin/print-volume-uuid b/bin/print-volume-uuid
--- a/bin/print-volume-uuid
+++ b/bin/print-volume-uuid
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} NAME
+
+Print UUID of given volume NAME."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} <name>
-
-Print UUID of given volume name." && exit
-
-diskutil info "$1" | grep 'Disk / Partition UUID:' | sed 's/^.*: *//'
+case "$1" in
+('') echo "${0##*/}: NAME missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) diskutil info "$1" | grep 'Disk / Partition UUID:' | sed 's/^.*: *//' ;;
+esac
diff --git a/bin/remove-links b/bin/remove-links
--- a/bin/remove-links
+++ b/bin/remove-links
@@ -1,15 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} DIR
+
+Remove all links from DIR."
 
 set -e
-
-[ "$1" = '--help' ] &&
-echo "Usage: ${0##*/} PATH
-
-Remove all links from PATH." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: PATH missing") && exit 1
-[ -d "$1" ] || (>&2 echo "${0##*/}: invalid path - '$1'" && exit 1)
-
-for file in "$1"/*
-do [ -L "$file" ] && rm "$file"
-done
+case "$1" in
+('') echo "${0##*/}: DIR name missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  [ -d "$1" ] || echo "${0##*/}: invalid directory name - '$1'" >&2 && exit 1
+  for file in "$1"/*
+  do [ -L "$file" ] && rm "$file"
+  done
+;;
+esac
diff --git a/bin/serve-http b/bin/serve-http
--- a/bin/serve-http
+++ b/bin/serve-http
@@ -1,13 +1,15 @@
 #! /bin/bash
+USAGE="Usage: ${0##*/} FILE [PORT]
+
+Serve FILE_NAME via HTTP."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} FILE_NAME [PORT]
-
-Serve FILE_NAME via HTTP." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: FILE_NAME missing") && exit 1
-
-while true; do
-	{ echo -e 'HTTP/1.1 200 OK\r\n'; cat "$1"; } | nc -l "${2:-8080}"
-done
+case "$1" in
+('') echo "${0##*/}: FILE name missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+	while true; do
+		{ echo -e 'HTTP/1.1 200 OK\r\n'; cat "$1"; } | nc -l "${2:-8080}"
+	done
+;;
+esac
diff --git a/bin/set-system-name b/bin/set-system-name
--- a/bin/set-system-name
+++ b/bin/set-system-name
@@ -1,15 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} NAME
+
+Set system NAME. (May require password.)"
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} NAME
-
-Set system NAME. (May require password.)" && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: NAME missing") && exit 1
-
-readonly NAME="$*"
-sudo scutil --set ComputerName "$NAME"
-sudo scutil --set HostName "$NAME"
-sudo scutil --set LocalHostName "$NAME"
-sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$NAME"
+case "$1" in
+('') echo "${0##*/}: NAME missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  sudo scutil --set ComputerName "$1"
+  sudo scutil --set HostName "$1"
+  sudo scutil --set LocalHostName "$1"
+  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$1"
+;;
+esac
diff --git a/bin/show-msg b/bin/show-msg
--- a/bin/show-msg
+++ b/bin/show-msg
@@ -1,11 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} MESSAGE [TITLE]
+
+Display a notification message."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} MESSAGE [TITLE]
-
-Display a notification message." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
-
-terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
+case "$1" in
+('') echo "${0##*/}: MESSAGE missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD ;;
+esac
diff --git a/bin/start-docker b/bin/start-docker
--- a/bin/start-docker
+++ b/bin/start-docker
@@ -1,14 +1,19 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Ensure Docker is started."
 
-Ensure that Docker is started." && exit
-
-(command -v docker >/dev/null 2>&1) || {
-  (>&2 echo "${0##*/}: Docker not installed") && exit 1
-}
-
-open --background -a Docker
-while [ -z "$(! docker stats --no-stream 2> /dev/null)" ]
-do sleep 1
-done
+set -e
+case "$1" in
+('')
+  (command -v docker >/dev/null 2>&1) || {
+    echo "${0##*/}: Docker not installed" >&2 && exit 1
+  }
+  open --background -a Docker
+  while [ -z "$(! docker stats --no-stream 2> /dev/null)" ]
+  do sleep 1
+  done
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/switch-autocorrect b/bin/switch-autocorrect
--- a/bin/switch-autocorrect
+++ b/bin/switch-autocorrect
@@ -1,23 +1,13 @@
 #! /bin/sh
-
-set -e
-
-case "$1" in
-(--help|-h|help)
-  echo "Usage: ${0##*/} [on|off|status]
+USAGE="Usage: ${0##*/} [on|off|status]
 
 Enable/disable text auto correction or show status."
-  ;;
-(on|1)
-  defaults write -g NSAutomaticSpellingCorrectionEnabled -bool true
-  ;;
-(off|0)
-  defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
-  ;;
-(status|'')
-  echo "State = $(defaults read -g NSAutomaticSpellingCorrectionEnabled)"
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
-  ;;
+
+set -e
+case "$1" in
+(on|1) defaults write -g NSAutomaticSpellingCorrectionEnabled -bool true ;;
+(off|0) defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false ;;
+(status|'') echo "state=$(defaults read -g NSAutomaticSpellingCorrectionEnabled)" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
diff --git a/bin/switch-background-throttle b/bin/switch-background-throttle
--- a/bin/switch-background-throttle
+++ b/bin/switch-background-throttle
@@ -1,36 +1,13 @@
 #! /bin/sh
-
-set -e
-
-[ "$1" = '--help' ] &&  echo "Usage: ${0##*/} [on|off]
-
-" && exit
-
-if [ "$1" = 'off' ]
-then
-else
-fi
-
-#! /bin/sh
-
-set -e
-
-case "$1" in
-(--help|-h|help)
-  echo "Usage: ${0##*/} [on|off]
+USAGE="Usage: ${0##*/} [on|off]
 
 Enable/disable background process throddeling (May require password.)"
-  ;;
-(on|1)
-  sudo sysctl debug.lowpri_throttle_enabled=0
-  ;;
-(off|0)
-  sudo sysctl debug.lowpri_throttle_enabled=1
-  ;;
-('')
-  (>&2 echo "${0##*/}: option missing") && exit 1
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
-  ;;
+
+set -e
+case "$1" in
+(on|1) sudo sysctl debug.lowpri_throttle_enabled=0 ;;
+(off|0) sudo sysctl debug.lowpri_throttle_enabled=1 ;;
+(-h|--help) echo "$USAGE" ;;
+('') echo "${0##*/}: argument missing" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
diff --git a/bin/switch-firewall b/bin/switch-firewall
--- a/bin/switch-firewall
+++ b/bin/switch-firewall
@@ -1,23 +1,13 @@
 #! /bin/sh
-
-set -e
-
-case "$1" in
-(--help|-h|help)
-  echo "Usage: ${0##*/} [on|off|status]
+USAGE="Usage: ${0##*/} [on|off|status]
 
 Enable/disable firewall or show status. (May require password.)"
-  ;;
-(on|1)
-  sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
-  ;;
-(off|0)
-  sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
-  ;;
-(status|'')
-  sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
-  ;;
+
+set -e
+case "$1" in
+(on|1) sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on ;;
+(off|0) sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off ;;
+(status|'') sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
diff --git a/bin/switch-infrared b/bin/switch-infrared
--- a/bin/switch-infrared
+++ b/bin/switch-infrared
@@ -1,23 +1,13 @@
 #! /bin/sh
-
-set -e
-
-case "$1" in
-(--help|-h|help)
-  echo "Usage: ${0##*/} [on|off|status]
+USAGE="Usage: ${0##*/} [on|off|status]
 
 Enable/disable infrared receiver or show status (default)."
-  ;;
-(on|1)
-  defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -int 1
-  ;;
-(off|0)
-  defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -int 0
-  ;;
-(status|'')
-  echo "State = $(defaults read /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled)"
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
-  ;;
+
+set -e
+case "$1" in
+(on|1) defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -int 1 ;;
+(off|0) defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -int 0 ;;
+(status|'') echo "state=$(defaults read /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled)" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
diff --git a/bin/switch-wlan b/bin/switch-wlan
--- a/bin/switch-wlan
+++ b/bin/switch-wlan
@@ -1,23 +1,13 @@
 #! /bin/sh
-
-set -e
-
-case "$1" in
-(--help|-h|help)
-  echo "Usage: ${0##*/} [on|off|status]
+USAGE="Usage: ${0##*/} [on|off|status]
 
 Switch WLAN on/off or return the current status."
-  ;;
-(on|1)
-  networksetup -setairportpower en0 on
-  ;;
-(off|0)
-  networksetup -setairportpower en0 off
-  ;;
-(status|'')
-  echo "State = $(networksetup -getairportpower en0 | grep -oE 'On|Off' | tr '[:upper:]' '[:lower:]')"
-  ;;
-(*)
-  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
-  ;;
+
+set -e
+case "$1" in
+(on|1) networksetup -setairportpower en0 on ;;
+(off|0) networksetup -setairportpower en0 off ;;
+(status|'') echo "state=$(networksetup -getairportpower en0 | grep -oE 'On|Off' | tr '[:upper:]' '[:lower:]')" ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
 esac
diff --git a/bin/update-all b/bin/update-all
--- a/bin/update-all
+++ b/bin/update-all
@@ -1,15 +1,18 @@
 #! /bin/sh
-
-set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} [--no-system]
+USAGE="Usage: ${0##*/} [--no-system]
 
 Update System, Homebrew, Homebrew bundles, ASDF and Ruby gems.
-(May require password.)" && exit
+(May require password.)"
 
-if ! [ "$1" = '-s' ] && ! [ "$1" = '--no-system' ]
-then echo '🆙 update system stuff' && update-system
-fi
+set -e
+case "$1" in
+(-S|--no-system) SYSTEM=0 ;;
+(-h|--help) echo "$USAGE" && exit ;;
+('') SYSTEM=1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
+
+[ "$SYSTEM" = "1" ] && echo '🆙 update system stuff' && update-system
 echo '🆙 update Brew stuff' && update-brew
 echo '🆙 update ASDF stuff' && update-asdf
 echo '🆙 update Ruby stuff' && update-ruby
diff --git a/bin/update-asdf b/bin/update-asdf
--- a/bin/update-asdf
+++ b/bin/update-asdf
@@ -1,11 +1,15 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Update ASDF and stuff."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Update ASDF and stuff." && exit
-
-asdf plugin update --all
-asdf install nodejs latest
-asdf install ruby latest
+case "$1" in
+('')
+  asdf plugin update --all
+  asdf install nodejs latest
+  asdf install ruby latest
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/update-brew b/bin/update-brew
--- a/bin/update-brew
+++ b/bin/update-brew
@@ -1,12 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Update Homebrew and Homebrew bundles."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Update Homebrew and Homebrew bundles." && exit
-
-brew update
-brew bundle --global
-brew upgrade
-brew upgrade --cask
+case "$1" in
+('')
+  brew update
+  brew bundle --global
+  brew upgrade
+  brew upgrade --cask
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/update-ruby b/bin/update-ruby
--- a/bin/update-ruby
+++ b/bin/update-ruby
@@ -1,10 +1,14 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Update Ruby gems."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Update Ruby gems." && exit
-
-gem update --system --no-document
-gem update --no-document
+case "$1" in
+('')
+  gem update --system --no-document
+  gem update --no-document
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/update-system b/bin/update-system
--- a/bin/update-system
+++ b/bin/update-system
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Update System. (May require password.)"
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Update System. (May require password.)" && exit
-
-sudo softwareupdate -i -a
+case "$1" in
+('') sudo softwareupdate -i -a ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/view-colors-sample b/bin/view-colors-sample
--- a/bin/view-colors-sample
+++ b/bin/view-colors-sample
@@ -1,15 +1,18 @@
 #! /bin/bash
+USAGE="Usage: ${0##*/}
+
+View colors."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-View colors." && exit
-
-CLEAR=$(tput op)
-COLS=$(tput cols)
-
-for i in {0..255} ; do
-	printf "$(tput setaf "$i" ; tput setab "$i") %03d $CLEAR" "$i"
-	{ test "$(((i + 1) % (COLS / 5)))" -eq '0' || test "$i" -eq '255'; } && echo
-done
+case "$1" in
+('')
+	CLEAR=$(tput op)
+	COLS=$(tput cols)
+	for i in {0..255} ; do
+		printf "$(tput setaf "$i" ; tput setab "$i") %03d $CLEAR" "$i"
+		{ test "$(((i + 1) % (COLS / 5)))" -eq '0' || test "$i" -eq '255'; } && echo
+	done
+;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/view-csv b/bin/view-csv
--- a/bin/view-csv
+++ b/bin/view-csv
@@ -1,11 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} FILE
+
+View given CSV FILE."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} CSV_FILE
-
-View given CSV_FILE." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: CSV_FILE missing") && exit 1
-
-sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
+case "$1" in
+('') echo "${0##*/}: FILE name missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S ;;
+esac
diff --git a/bin/view-fefe b/bin/view-fefe
--- a/bin/view-fefe
+++ b/bin/view-fefe
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Displays Fefes blog."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Displays Fefes blog." && exit
-
-fetch-web https://blog.fefe.de | convert-html-text | less
+case "$1" in
+('') fetch-web https://blog.fefe.de | convert-html-text | less ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/bin/view-star-wars b/bin/view-star-wars
--- a/bin/view-star-wars
+++ b/bin/view-star-wars
@@ -1,9 +1,11 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
+
+Watch StarWars in ASCII from blinkenlights.nl."
 
 set -e
-
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
-
-Watch StarWars in ASCII from blinkenlights.nl." && exit
-
-ncat towel.blinkenlights.nl 23
+case "$1" in
+('') ncat towel.blinkenlights.nl 23 ;;
+(-h|--help) echo "$USAGE" ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+esac
diff --git a/init/aws-renew b/init/aws-renew
--- a/init/aws-renew
+++ b/init/aws-renew
@@ -1,25 +1,27 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/} 2FACODE
+
+Renew AWS session."
 
 set -e
+case "$1" in
+('') echo "${0##*/}: 2FACODE missing" >&2 && exit 1 ;;
+(-h|--help) echo "$USAGE" ;;
+(*)
+  readonly MFA_USER="mike.blumtritt"
+  readonly MFA_TOKEN="$1"
+  readonly MFA_PROFILE="${2:-default}"
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/} 2FACODE
+  MFA_CALLER_ID=$(aws sts get-caller-identity --profile "${MFA_USER}" | jq -r '.Arn | split("/")[1]')
+  MFA_DEVICES=$(aws iam list-mfa-devices --profile "${MFA_USER}" --user-name "${MFA_CALLER_ID}")
+  MFA_SERIAL_NUMBER=$(echo "${MFA_DEVICES}"| jq -r '.MFADevices[0].SerialNumber')
+  MFA_SESSION=$(aws sts --profile "${MFA_USER}" get-session-token --duration-seconds 28800 --serial-number "${MFA_SERIAL_NUMBER}" --token-code "${MFA_TOKEN}")
+  MFA_ACCESS_KEY_ID=$(echo "${MFA_SESSION}" | jq -r '.Credentials.AccessKeyId')
+  MFA_SECRET_ACCESS_KEY=$(echo "${MFA_SESSION}" | jq -r '.Credentials.SecretAccessKey')
+  MFA_SESSION_TOKEN=$(echo "${MFA_SESSION}" | jq -r '.Credentials.SessionToken')
 
-Renew AWS session." && exit
-
-[ $# = 0 ] && (>&2 echo "${0##*/}: 2FACODE missing") && exit 1
-
-readonly MFA_USER="mike.blumtritt"
-readonly MFA_TOKEN="$1"
-readonly MFA_PROFILE="${2:-default}"
-
-MFA_CALLER_ID=$(aws sts get-caller-identity --profile "${MFA_USER}" | jq -r '.Arn | split("/")[1]')
-MFA_DEVICES=$(aws iam list-mfa-devices --profile "${MFA_USER}" --user-name "${MFA_CALLER_ID}")
-MFA_SERIAL_NUMBER=$(echo "${MFA_DEVICES}"| jq -r '.MFADevices[0].SerialNumber')
-MFA_SESSION=$(aws sts --profile "${MFA_USER}" get-session-token --duration-seconds 28800 --serial-number "${MFA_SERIAL_NUMBER}" --token-code "${MFA_TOKEN}")
-MFA_ACCESS_KEY_ID=$(echo "${MFA_SESSION}" | jq -r '.Credentials.AccessKeyId')
-MFA_SECRET_ACCESS_KEY=$(echo "${MFA_SESSION}" | jq -r '.Credentials.SecretAccessKey')
-MFA_SESSION_TOKEN=$(echo "${MFA_SESSION}" | jq -r '.Credentials.SessionToken')
-
-aws configure set --profile "${MFA_PROFILE}" aws_access_key_id "${MFA_ACCESS_KEY_ID}"
-aws configure set --profile "${MFA_PROFILE}" aws_secret_access_key "${MFA_SECRET_ACCESS_KEY}"
-aws configure set --profile "${MFA_PROFILE}" aws_session_token "${MFA_SESSION_TOKEN}"
+  aws configure set --profile "${MFA_PROFILE}" aws_access_key_id "${MFA_ACCESS_KEY_ID}"
+  aws configure set --profile "${MFA_PROFILE}" aws_secret_access_key "${MFA_SECRET_ACCESS_KEY}"
+  aws configure set --profile "${MFA_PROFILE}" aws_session_token "${MFA_SESSION_TOKEN}"
+;;
+esac
