Tidy-up shell commands

diff --git a/bin/ask-msg b/bin/ask-msg
--- a/bin/ask-msg
+++ b/bin/ask-msg
@@ -2,13 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} MESSAGE [TITLE]
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} MESSAGE [TITLE]
 
 Request a user action.
 "
-elif [ $# = 0 ]; then
-	echo "${0##*/}: MESSAGE missing" >&2
-	exit 1
-else
-  osascript -e "tell app \"System Events\" to display dialog \"$1\" with title \"${2-Notification}\"" > /dev/null 2>&1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
+else osascript -e "tell app \"System Events\" to display dialog \"$1\" with title \"${2-Notification}\"" > /dev/null 2>&1
 fi
diff --git a/bin/aws-renew b/bin/aws-renew
--- a/bin/aws-renew
+++ b/bin/aws-renew
@@ -2,14 +2,13 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} 2FACODE
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} 2FACODE
 
 Renew AWS session.
 "
 elif [ $# = 0 ]
-then
-	echo "${0##*/}: 2FACODE missing" >&2
-	exit 1
+then (>&2 echo "${0##*/}: 2FACODE missing") && exit 1
 else
 	readonly MFA_USER="mike.blumtritt"
 	readonly MFA_TOKEN="$1"
@@ -25,7 +24,4 @@ else
   aws configure set --profile "${MFA_PROFILE}" aws_access_key_id "${MFA_ACCESS_KEY_ID}"
 	aws configure set --profile "${MFA_PROFILE}" aws_secret_access_key "${MFA_SECRET_ACCESS_KEY}"
 	aws configure set --profile "${MFA_PROFILE}" aws_session_token "${MFA_SESSION_TOKEN}"
-
-	echo "AWS credentials actualized"
-	. "$HOME/.local/init/aws"
 fi
diff --git a/bin/convert-mp4-m4r b/bin/convert-mp4-m4r
--- a/bin/convert-mp4-m4r
+++ b/bin/convert-mp4-m4r
@@ -2,13 +2,13 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} FILE
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} FILE
 
 Convert MP3 ausio FILE to ringtome M4R.
 "
-elif [ $# = 0 ]; then
-	echo "${0##*/}: FILE missing" >&2
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: FILE missing") && exit 1
 else
 	for file in "$@"
 	do
diff --git a/bin/create-disk-image b/bin/create-disk-image
--- a/bin/create-disk-image
+++ b/bin/create-disk-image
@@ -2,17 +2,18 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} [--encrypt] DIR [NAME]
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} [--encrypt] DIR [NAME]
 
 Create disk image from DIR named NAME, optionally encrypted with PASSWD.
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: DIR missing")
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: DIR missing") && exit 1
 else
   OPTIONS="-nospotlight -noanyowners"
   TYPE=volume
-  if [ "$1" = "--encrypt" ] || [ "$1" = "-e" ]; then
+  if [ "$1" = "--encrypt" ] || [ "$1" = "-e" ]
+  then
     TYPE="encrypted volume"
     OPTIONS="-encryption AES-256 -stdinpass $OPTIONS"
     shift
@@ -21,8 +22,8 @@ else
   readonly BASENAME="${DIR##*/}"
   OPTIONS="-srcfolder \"$DIR\" -ov \"./$BASENAME.dmg\" $OPTIONS"
   shift
-  if [ $# = 0 ]; then
-    echo "create $TYPE of $DIR"
+  if [ $# = 0 ]
+  then echo "create $TYPE of $DIR"
   else
     echo "create $TYPE \"$1\" of $DIR"
     OPTIONS="$OPTIONS -volname \"$1\""
diff --git a/bin/download-audio b/bin/download-audio
--- a/bin/download-audio
+++ b/bin/download-audio
@@ -3,15 +3,14 @@
 set -e
 readonly TDIR="$HOME/Downloads"
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} URL
 
 Download a audio or playlist as MP3 from given URL to '$TDIR'.
 "
-elif [ $# = 0 ]; then
-	echo "${0##*/}: URL missing" >&2
-	exit 1
-else
-  yt-dlp \
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: URL missing") && exit 1
+else yt-dlp \
     --extract-audio --audio-format m4a --audio-quality 0 \
     --embed-metadata \
     --embed-thumbnail \
diff --git a/bin/download-file b/bin/download-file
--- a/bin/download-file
+++ b/bin/download-file
@@ -3,14 +3,14 @@
 set -e
 readonly TDIR="$HOME/Downloads"
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} URL
 
 Download a file from given URL to '$TDIR'.
 "
   exit 0
-elif [ $# = 0 ]; then
-	echo "${0##*/}: URL missing" >&2
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: URL missing") && exit 1
 else
   trap 'exit 130' INT HUP TERM
   mkdir -p "$TDIR"
diff --git a/bin/edit-text b/bin/edit-text
--- a/bin/edit-text
+++ b/bin/edit-text
@@ -2,21 +2,19 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} [FILE | NAME]
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} [FILE | NAME]
 
 Edit given FILE or project NAME.
 "
-elif [ $# = 0 ]; then
-	echo "${0##*/}: FILE | NAME missing" >&2
-	exit 1
-elif [ -e "$1" ]; then
-  code "$1"
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: FILE | NAME missing") && exit 1
+elif [ -e "$1" ]
+then code "$1"
 else
   PROJECT="$(list-projects --top "$1")"
-  if [ "$PROJECT" = "" ]; then
-  	echo "${0##*/}: no such project - $1" >&2
-  	exit 2
-  else
-    code "$PROJECT"
+  if [ "$PROJECT" = "" ]
+  then (>&2 echo "${0##*/}: no such project - $1") && exit 2
+  else code "$PROJECT"
   fi
 fi
diff --git a/bin/fetch-web b/bin/fetch-web
--- a/bin/fetch-web
+++ b/bin/fetch-web
@@ -2,13 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} URL
 
 Display a file from given URL.
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: URL missing")
-	exit 1
-else
-	curl -sLN "$*"
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: URL missing") && exit 1
+else curl -sLN "$*"
 fi
diff --git a/bin/flush-routes b/bin/flush-routes
--- a/bin/flush-routes
+++ b/bin/flush-routes
@@ -2,13 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} INTERFACE
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} INTERFACE
 
 Flush routes for your INTERFACE (like en0, en1, ...). (May require password.)
 "
-elif [ $# = 0 ]; then
-  (>&2 echo "${0##*/}: name of INTERFACE missing")
-  exit 1
-else
-  sudo ifconfig "$1" down && sudo route flush && sudo ifconfig "$1" up
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: name of INTERFACE missing") && exit 1
+else sudo ifconfig "$1" down && sudo route flush && sudo ifconfig "$1" up
 fi
diff --git a/bin/list-whois b/bin/list-whois
--- a/bin/list-whois
+++ b/bin/list-whois
@@ -2,13 +2,13 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} URL
 
 Display WHOIS rrecord about given URL or domain.
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: URL missing")
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: URL missing") && exit 1
 else
 	domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
 	[ -z "$domain" ] && domain=$1
diff --git a/bin/play-audio b/bin/play-audio
--- a/bin/play-audio
+++ b/bin/play-audio
@@ -2,14 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} FILE
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} FILE
 
 Plays given audio FILE.
 "
 elif [ $# = 0 ]
-then
-	(>&2 echo "${0##*/}: FILE missing")
-	exit 1
-else
-  afplay -q 1 "$*"
+then (>&2 echo "${0##*/}: FILE missing") && exit 1
+else afplay -q 1 $@
 fi
diff --git a/bin/print-search-url b/bin/print-search-url
--- a/bin/print-search-url
+++ b/bin/print-search-url
@@ -2,24 +2,25 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} TERM
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} TERM
 
 Print search URL.
 
 options:
-   -g, --google    print Google search URL (default)
-   -y, --youtube   print YouTube search URL
-   -w, --wiki      print Wikipedia search URL
-   -a, --alpha     print Wolfram Alpha search URL
-   -l, --leo       print LeoDictionary search URL
-   -h, --github    print GitHub search URL
-   -i, --image     print image search URL (Google)
-   -v, --video     print vide search URL (YouTube)
-   -d, --dict      print vide search URL (Leo)
+   -a, --alpha        print Wolfram Alpha search URL
+   -d, --dict         print english/german term search URL (Leo)
+   -g, --google       print Google search URL (default)
+   -h, --github       print GitHub search URL
+   -i, --image        print image search URL (Google)
+   -l, --leo          print LeoDictionary search URL
+   -p, --perplexity   print Perplexity search URL
+   -v, --video        print video search URL (YouTube)
+   -w, --wiki         print Wikipedia search URL
+   -y, --youtube      print YouTube search URL
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: TERM missing")
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: TERM missing") && exit 1
 else
   term=''
   url='https://www.google.de/search?hl=de&as_qdr=all&as_occt=any&num=100&as_q='
@@ -48,11 +49,13 @@ else
     -h|--github)
       url='https://github.com/search?q='
       ;;
+    -p|--perplexity)
+      url='https://www.perplexity.ai/search?q='
+      ;;
     *)
-      if [ "$term" = "" ]; then
-        term="$arg"
-      else
-        term="$term $arg"
+      if [ "$term" = "" ]
+      then term="$arg"
+      else term="$term $arg"
       fi
       ;;
     esac
diff --git a/bin/serve-http b/bin/serve-http
--- a/bin/serve-http
+++ b/bin/serve-http
@@ -2,13 +2,13 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} FILE_NAME [PORT]
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} FILE_NAME [PORT]
 
 Serve FILE_NAME via HTTP.
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: FILE_NAME missing")
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: FILE_NAME missing") && exit 1
 else
 	while true; do
 		{ echo -e 'HTTP/1.1 200 OK\r\n'; cat "$1"; } | nc -l "${2:-8080}"
diff --git a/bin/set-system-name b/bin/set-system-name
--- a/bin/set-system-name
+++ b/bin/set-system-name
@@ -2,13 +2,13 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} NAME
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} NAME
 
 Set system NAME. (May require password.)
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: NAME missing")
-	exit 1
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: NAME missing") && exit 1
 else
 	readonly NAME="$*"
 	sudo scutil --set ComputerName "$NAME"
diff --git a/bin/show-msg b/bin/show-msg
--- a/bin/show-msg
+++ b/bin/show-msg
@@ -2,13 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} MESSAGE [TITLE]
+if [ "$1" = '--help' ]
+then echo "Usage: ${0##*/} MESSAGE [TITLE]
 
 Display a notification message.
 "
-elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: MESSAGE missing")
-	exit 1
-else
-  terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
+elif [ $# = 0 ]
+then (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
+else terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
 fi
