Tidy-up commands

diff --git a/bin/clean-system b/bin/clean-system
--- a/bin/clean-system
+++ b/bin/clean-system
@@ -19,17 +19,32 @@ case "$1" in
 		kill -0 "$$" || exit
 	done 2>/dev/null &
 
-	(command -v brew >/dev/null 2>&1) && echo '🗑️ clean brew stuff...' && clean-brew
-	(command -v docker >/dev/null 2>&1) && echo '🗑️ clean Docker...' && clean-docker
-	(command -v npm >/dev/null 2>&1) && echo '🗑️ clean NPM...' && clean-npm
-	(command -v yarn >/dev/null 2>&1) && echo '🗑️ clean Yarn...' && clean-yarn
-	(command -v gem >/dev/null 2>&1) && echo '🗑️ clean gems...' && clean-gems
+	(command -v brew >/dev/null 2>&1) && (
+		echo '🗑️ clean brew stuff...'
+		clean-brew
+	)
+	(command -v docker >/dev/null 2>&1) && (
+		echo '🗑️ clean Docker...'
+		clean-docker
+	)
+	(command -v npm >/dev/null 2>&1) && (
+		echo '🗑️ clean NPM...'
+		clean-npm
+	)
+	(command -v yarn >/dev/null 2>&1) && (
+		echo '🗑️ clean Yarn...'
+		clean-yarn
+	)
+	(command -v gem >/dev/null 2>&1) && (
+		echo '🗑️ clean gems...'
+		clean-gems
+	)
 
-	echo '🗑️ remove system log files...' && clean-logs
-	echo '🗑️ clean all library caches...' && clean-caches
-	echo '🗑️ cleanup XCode derived data and archives...' && clean-xcode
-	echo '🗑️ clean Trashes...' && clean-trashes
+	echo '🗑️ remove system log files...' ; clean-logs
+	echo '🗑️ clean all library caches...' ; clean-caches
+	echo '🗑️ cleanup XCode derived data and archives...' ; clean-xcode
+	echo '🗑️ clean Trashes...' ; clean-trashes
 ;;
 (-h|--help) echo "$USAGE" ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
 esac
diff --git a/bin/edit-text b/bin/edit-text
--- a/bin/edit-text
+++ b/bin/edit-text
@@ -5,13 +5,13 @@ Edit given FILE or project NAME."
 
 set -e
 case "$1" in
-('') echo "${0##*/}: FILE or NAME missing " >&2 && exit 1 ;;
+('') echo "${0##*/}: FILE or NAME missing " >&2 ; exit 1 ;;
 (-h|--help) echo "$USAGE" ;;
 (*)
   if [ -r "$1" ]
   then code "$1"
   else
-    PROJECT="$(list-projects "$1")" || (>&2 echo "${0##*/}: no such project - $1" && exit 2)
+    PROJECT="$(list-projects "$1")" || (>&2 echo "${0##*/}: no such project - $1" ; exit 2)
     code "$PROJECT"
   fi
 ;;
diff --git a/bin/print-search-url b/bin/print-search-url
--- a/bin/print-search-url
+++ b/bin/print-search-url
@@ -24,9 +24,9 @@ case "$1" in
 (-p|--perplexity) url='https://www.perplexity.ai/search?q=' ;;
 (-v|--video|-y|--youtube) url='https://www.youtube.com/results?search_query=' ;;
 (-w|--wiki|--wikipedia) url='https://de.wikipedia.org/w/index.php?fulltext=1&search=' ;;
-(--help) echo "$USAGE" && exit ;;
-('') echo "${0##*/}: argument missing" >&2 && exit 1 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+(--help) echo "$USAGE" ; exit ;;
+('') echo "${0##*/}: argument missing" >&2 ; exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
 esac
 shift
 echo "$url$(echo "$@" | convert-text-uri)"
diff --git a/bin/start-docker b/bin/start-docker
--- a/bin/start-docker
+++ b/bin/start-docker
@@ -7,7 +7,7 @@ set -e
 case "$1" in
 ('')
   (command -v docker >/dev/null 2>&1) || {
-    echo "${0##*/}: Docker not installed" >&2 && exit 1
+    echo "${0##*/}: Docker not installed" >&2 ; exit 1
   }
   open --background -a Docker
   while [ -z "$(! docker stats --no-stream 2> /dev/null)" ]
@@ -15,5 +15,5 @@ case "$1" in
   done
 ;;
 (-h|--help) echo "$USAGE" ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
 esac
diff --git a/bin/update-all b/bin/update-all
--- a/bin/update-all
+++ b/bin/update-all
@@ -7,12 +7,12 @@ Update System, Homebrew, Homebrew bundles, ASDF and Ruby gems.
 set -e
 case "$1" in
 (-S|--no-system) SYSTEM=0 ;;
-(-h|--help) echo "$USAGE" && exit ;;
+(-h|--help) echo "$USAGE" ; exit ;;
 ('') SYSTEM=1 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
 esac
 
-[ "$SYSTEM" = "1" ] && echo '🆙 update system stuff' && update-system
-echo '🆙 update Brew stuff' && update-brew
-echo '🆙 update ASDF stuff' && update-asdf
-echo '🆙 update Ruby stuff' && update-ruby
+[ "$SYSTEM" = "1" ] && (echo '🆙 update system stuff' ; update-system)
+echo '🆙 update Brew stuff' ; update-brew
+echo '🆙 update ASDF stuff' ; update-asdf
+echo '🆙 update Ruby stuff' ; update-ruby
diff --git a/bin/view-colors-sample b/bin/view-colors-sample
--- a/bin/view-colors-sample
+++ b/bin/view-colors-sample
@@ -14,5 +14,5 @@ case "$1" in
 	done
 ;;
 (-h|--help) echo "$USAGE" ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 && exit 1 ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
 esac
diff --git a/init/aws-export b/init/aws-export
--- a/init/aws-export
+++ b/init/aws-export
@@ -1,10 +1,16 @@
 #! /bin/sh
+USAGE="Usage: ${0##*/}
 
-[ "$1" = '--help' ] && echo "Usage: ${0##*/}
+Export AWS related environment variables."
 
-Export AWS related environment variables." && exit
-
-AWS_ACCESS_KEY_ID=$(awk -F "=" '/aws_access_key_id/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
-AWS_SECRET_ACCESS_KEY=$(awk -F "=" '/aws_secret_access_key/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
-AWS_SESSION_TOKEN=$(awk -F "=" '/aws_session_token/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
-export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
+set -e
+case "$1" in
+('')
+  AWS_ACCESS_KEY_ID=$(awk -F "=" '/aws_access_key_id/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
+  AWS_SECRET_ACCESS_KEY=$(awk -F "=" '/aws_secret_access_key/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
+  AWS_SESSION_TOKEN=$(awk -F "=" '/aws_session_token/ {print $2}' "$HOME/.aws/credentials" | tail -1 | xargs)
+  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
+;;
+(-h|--help) echo "$USAGE" ; exit ;;
+(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
+esac
