Prettify

diff --git a/bin/clean-system b/bin/clean-system
--- a/bin/clean-system
+++ b/bin/clean-system
@@ -44,5 +44,5 @@ Clean system. (May require password.)" ;;
 	echo '🗑️ cleanup XCode derived data and archives...' ; clean-xcode
 	echo '🗑️ clean Trashes...' ; clean-trashes
 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
+(*) >&2 echo "${0##*/}: invalid argument - $1" ; exit 1 ;;
 esac
diff --git a/bin/print-search-url b/bin/print-search-url
--- a/bin/print-search-url
+++ b/bin/print-search-url
@@ -26,8 +26,8 @@ Options:
 (-p|--perplexity) url='https://www.perplexity.ai/search?q=' ;;
 (-v|--video|-y|--youtube) url='https://www.youtube.com/results?search_query=' ;;
 (-w|--wiki|--wikipedia) url='https://de.wikipedia.org/w/index.php?fulltext=1&search=' ;;
-('') echo "${0##*/}: argument missing" >&2 ; exit 1 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
+('') >&2 echo "${0##*/}: argument missing" ; exit 1 ;;
+(*) >&2 echo "${0##*/}: invalid argument - $1" ; exit 1 ;;
 esac
 shift
 echo "$url$(echo "$@" | convert-text-uri)"
diff --git a/bin/start-docker b/bin/start-docker
--- a/bin/start-docker
+++ b/bin/start-docker
@@ -6,7 +6,7 @@ case "$1" in
 Ensure Docker is started." ;;
 ('')
   (command -v docker >/dev/null 2>&1) || {
-    echo "${0##*/}: Docker not installed" >&2
+    >&2 echo "${0##*/}: Docker not installed"
     exit 1
   }
   open --background -a Docker
@@ -14,5 +14,5 @@ Ensure Docker is started." ;;
   do sleep 1
   done
 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
+(*) >&2 echo "${0##*/}: invalid argument - $1" ; exit 1 ;;
 esac
diff --git a/bin/view-colors-sample b/bin/view-colors-sample
--- a/bin/view-colors-sample
+++ b/bin/view-colors-sample
@@ -12,5 +12,5 @@ View colors." ;;
 		{ test "$(((i + 1) % (COLS / 5)))" -eq '0' || test "$i" -eq '255'; } && echo
 	done
 ;;
-(*) echo "${0##*/}: invalid argument - $1" >&2 ; exit 1 ;;
+(*) >&2 echo "${0##*/}: invalid argument - $1" ; exit 1 ;;
 esac
