Refactor globally

diff --git a/bin/compare-disk-id b/bin/compare-disk-id
--- a/bin/compare-disk-id
+++ b/bin/compare-disk-id
@@ -2,19 +2,18 @@
 
 set -e
 
-if [ "$1" = '--help' ] || [ "$1" = '' ]
-then echo "Usage: ${0##*/} NAME
+[ "$1" = '--help' ]  && echo "Usage: ${0##*/} NAME
 
-Checks if disk NAME is the correct one.
-"
-else
-   # check partition UUID against regsitered id (stored in pass)
-   if [ "$(print-disk-uuid "$1")" = "$(print-system-secret "$1")" ]
-   then
-      # test if really mounted
-      if [ -f "/Volumes/$1/.fseventsd/fseventsd-uuid" ]
-      then exit 0
-      fi
+Checks if disk NAME is the correct one." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: NAME missing") && exit 1
+
+# check partition UUID against regsitered id (stored in pass)
+if [ "$(print-disk-uuid "$1")" = "$(print-system-secret "$1")" ]
+then
+   # test if really mounted
+   if [ -f "/Volumes/$1/.fseventsd/fseventsd-uuid" ]
+   then exit 0
    fi
-   exit 1
 fi
+exit 1
diff --git a/bin/convert-mp4-m4r b/bin/convert-mp4-m4r
--- a/bin/convert-mp4-m4r
+++ b/bin/convert-mp4-m4r
@@ -2,17 +2,14 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} FILE
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} FILE
 
-Convert MP3 ausio FILE to ringtome M4R.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: FILE missing") && exit 1
-else
-	for file in "$@"
-	do
-    file="${file%.*}"
-		afconvert "$file.mp3" "$file.m4r" -f m4af
-	done
-fi
+Convert MP3 ausio FILE to ringtome M4R." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: FILE missing") && exit 1
+
+for file in "$@"
+do
+	file="${file%.*}"
+	afconvert "$file.mp3" "$file.m4r" -f m4af
+done
diff --git a/bin/download-audio b/bin/download-audio
--- a/bin/download-audio
+++ b/bin/download-audio
@@ -3,19 +3,18 @@
 set -e
 readonly TDIR="$HOME/Downloads"
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} URL
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
 
-Download a audio or playlist as MP3 from given URL to '$TDIR'.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: URL missing") && exit 1
-else yt-dlp \
+Download a audio or playlist as MP3 from given URL to '$TDIR'." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
+
+mkdir -p "$TDIR"
+cd "$TDIR"
+yt-dlp \
     --extract-audio --audio-format m4a --audio-quality 0 \
     --embed-metadata \
     --embed-thumbnail \
     --concurrent-fragments 8 \
     --geo-bypass \
-    --output "$TDIR/%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s" \
     "$@"
-fi
diff --git a/bin/download-file b/bin/download-file
--- a/bin/download-file
+++ b/bin/download-file
@@ -3,17 +3,12 @@
 set -e
 readonly TDIR="$HOME/Downloads"
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} URL
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
 
-Download a file from given URL to '$TDIR'.
-"
-  exit 0
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: URL missing") && exit 1
-else
-  trap 'exit 130' INT HUP TERM
-  mkdir -p "$TDIR"
-  cd "$TDIR"
-  curl -sLNO "$@"
-fi
+Download a file from given URL to '$TDIR'." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
+
+mkdir -p "$TDIR"
+cd "$TDIR"
+curl -sLNO "$@"
diff --git a/bin/download-video b/bin/download-video
--- a/bin/download-video
+++ b/bin/download-video
@@ -3,16 +3,15 @@
 set -e
 readonly TDIR="$HOME/Downloads"
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} URL
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
 
-Download a video or video playlist from given URL to '$TDIR'.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: URL missing") && exit 1
-else yt-dlp \
+Download a video or video playlist from given URL to '$TDIR'." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
+
+mkdir -p "$TDIR"
+cd "$TDIR"
+yt-dlp \
     --concurrent-fragments 8 \
     --geo-bypass \
-    --output "$TDIR/%(title)s.%(ext)s" \
     "$@"
-fi
diff --git a/bin/edit-text b/bin/edit-text
--- a/bin/edit-text
+++ b/bin/edit-text
@@ -2,19 +2,15 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} [FILE | NAME]
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} [FILE | NAME]
 
-Edit given FILE or project NAME.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: FILE | NAME missing") && exit 1
-elif [ -e "$1" ]
+Edit given FILE or project NAME." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: FILE | NAME missing") && exit 1
+
+if [ -e "$1" ]
 then code "$1"
 else
-  PROJECT="$(list-projects --top "$1")"
-  if [ "$PROJECT" = "" ]
-  then (>&2 echo "${0##*/}: no such project - $1") && exit 2
-  else code "$PROJECT"
-  fi
+  PROJECT="$(list-projects "$1")" || (>&2 echo "${0##*/}: no such project - $1" && exit 2)
+  code "$PROJECT"
 fi
diff --git a/bin/fetch-web b/bin/fetch-web
--- a/bin/fetch-web
+++ b/bin/fetch-web
@@ -2,12 +2,10 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} URL
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} URL
 
-Display a file from given URL.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: URL missing") && exit 1
-else curl -sLN "$*"
-fi
+Display a file from given URL." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: URL missing") && exit 1
+
+curl -sLN $@
diff --git a/bin/print-search-url b/bin/print-search-url
--- a/bin/print-search-url
+++ b/bin/print-search-url
@@ -2,64 +2,52 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} TERM
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} <OPTION> [TERM]
 
 Print search URL.
 
-options:
+Options:
    -a, --alpha        print Wolfram Alpha search URL
    -d, --dict         print english/german term search URL (Leo)
    -g, --google       print Google search URL (default)
    -h, --github       print GitHub search URL
    -i, --image        print image search URL (Google)
-   -l, --leo          print LeoDictionary search URL
    -p, --perplexity   print Perplexity search URL
    -v, --video        print video search URL (YouTube)
    -w, --wiki         print Wikipedia search URL
-   -y, --youtube      print YouTube search URL
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: TERM missing") && exit 1
-else
-  term=''
+   -y, --youtube      print YouTube search URL" && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: OPTION missing") && exit 1
+
+case "$1" in
+(-a|--alpha)
+  url='https://www.wolframalpha.com/input/?i='
+  ;;
+(-d|--dict)
+  url='https://pocket.dict.cc/?s='
+  ;;
+(-g|--google)
   url='https://www.google.de/search?hl=de&as_qdr=all&as_occt=any&num=100&as_q='
+  ;;
+(-h|--github)
+  url='https://github.com/search?q='
+  ;;
+(-i|--image)
+  url='https://www.google.de/search?source=lnms&tbm=isch&sa=X&ei=qWBvVcrKMYWAUa3BgZAF&ved=0CAgQ_AUoAg&biw=1075&bih=728&q='
+  ;;
+(-p|--perplexity)
+  url='https://www.perplexity.ai/search?q='
+  ;;
+(-v|--video|-y|--youtube)
+  url='https://www.youtube.com/results?search_query='
+  ;;
+(-w|--wiki|--wikipedia)
+  url='https://de.wikipedia.org/w/index.php?fulltext=1&search='
+  ;;
+(*)
+  (>&2 echo "${0##*/}: unknonw option - $1") && exit 1
+  ;;
+esac
 
-	for arg in "$@"
-	do
-    case "$arg" in
-    -g|--google)
-      url='https://www.google.de/search?hl=de&as_qdr=all&as_occt=any&num=100&as_q='
-      ;;
-    -i|--image)
-      url='https://www.google.de/search?source=lnms&tbm=isch&sa=X&ei=qWBvVcrKMYWAUa3BgZAF&ved=0CAgQ_AUoAg&biw=1075&bih=728&q='
-      ;;
-    -v|--video|-y|--youtube)
-      url='https://www.youtube.com/results?search_query='
-      ;;
-    -w|--wiki|--wikipedia)
-      url='https://de.wikipedia.org/w/index.php?fulltext=1&search='
-      ;;
-    -a|--alpha)
-      url='https://www.wolframalpha.com/input/?i='
-      ;;
-    -d|--dict|-l|--leo)
-      url='https://pocket.dict.cc/?s='
-      ;;
-    -h|--github)
-      url='https://github.com/search?q='
-      ;;
-    -p|--perplexity)
-      url='https://www.perplexity.ai/search?q='
-      ;;
-    *)
-      if [ "$term" = "" ]
-      then term="$arg"
-      else term="$term $arg"
-      fi
-      ;;
-    esac
-	done
-
-  echo "$url$(echo "$term" | convert-text-uri)"
-fi
+shift
+echo "$url$(echo "$@" | convert-text-uri)"
diff --git a/bin/serve-http b/bin/serve-http
--- a/bin/serve-http
+++ b/bin/serve-http
@@ -2,15 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} FILE_NAME [PORT]
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} FILE_NAME [PORT]
 
-Serve FILE_NAME via HTTP.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: FILE_NAME missing") && exit 1
-else
-	while true; do
-		{ echo -e 'HTTP/1.1 200 OK\r\n'; cat "$1"; } | nc -l "${2:-8080}"
-	done
-fi
+Serve FILE_NAME via HTTP." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: FILE_NAME missing") && exit 1
+
+while true; do
+	{ echo -e 'HTTP/1.1 200 OK\r\n'; cat "$1"; } | nc -l "${2:-8080}"
+done
diff --git a/bin/set-system-name b/bin/set-system-name
--- a/bin/set-system-name
+++ b/bin/set-system-name
@@ -2,17 +2,15 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} NAME
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} NAME
 
-Set system NAME. (May require password.)
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: NAME missing") && exit 1
-else
-	readonly NAME="$*"
-	sudo scutil --set ComputerName "$NAME"
-	sudo scutil --set HostName "$NAME"
-	sudo scutil --set LocalHostName "$NAME"
-	sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$NAME"
-fi
+Set system NAME. (May require password.)" && exit
+
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: NAME missing") && exit 1
+
+readonly NAME="$*"
+sudo scutil --set ComputerName "$NAME"
+sudo scutil --set HostName "$NAME"
+sudo scutil --set LocalHostName "$NAME"
+sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$NAME"
diff --git a/bin/show-msg b/bin/show-msg
--- a/bin/show-msg
+++ b/bin/show-msg
@@ -2,12 +2,10 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} MESSAGE [TITLE]
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} MESSAGE [TITLE]
 
-Display a notification message.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
-else terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
-fi
+Display a notification message." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: MESSAGE missing") && exit 1
+
+terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
diff --git a/bin/switch-background-throttle b/bin/switch-background-throttle
--- a/bin/switch-background-throttle
+++ b/bin/switch-background-throttle
@@ -2,12 +2,35 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} [on|off]
+[ "$1" = '--help' ] &&  echo "Usage: ${0##*/} [on|off]
 
-Enable/disable background process throddeling (May require password.)
-"
-elif [ "$1" = 'off' ]
-then sudo sysctl debug.lowpri_throttle_enabled=0
-else sudo sysctl debug.lowpri_throttle_enabled=1
+" && exit
+
+if [ "$1" = 'off' ]
+then
+else
 fi
+
+#! /bin/sh
+
+set -e
+
+case "$1" in
+(--help|-h|help)
+  echo "Usage: ${0##*/} [on|off]
+
+Enable/disable background process throddeling (May require password.)"
+  ;;
+(on|1)
+  sudo sysctl debug.lowpri_throttle_enabled=0
+  ;;
+(off|0)
+  sudo sysctl debug.lowpri_throttle_enabled=1
+  ;;
+('')
+  (>&2 echo "${0##*/}: option missing") && exit 1
+  ;;
+(*)
+  (>&2 echo "${0##*/}: unknown option - $1") && exit 1
+  ;;
+esac
diff --git a/bin/view-csv b/bin/view-csv
--- a/bin/view-csv
+++ b/bin/view-csv
@@ -2,12 +2,10 @@
 
 set -e
 
-if [ "$1" = '--help' ]
-then echo "Usage: ${0##*/} CSV_FILE
+[ "$1" = '--help' ] && echo "Usage: ${0##*/} CSV_FILE
 
-View given CSV_FILE.
-"
-elif [ $# = 0 ]
-then (>&2 echo "${0##*/}: CSV_FILE missing") && exit 1
-else sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
-fi
+View given CSV_FILE." && exit
+
+[ $# = 0 ] && (>&2 echo "${0##*/}: CSV_FILE missing") && exit 1
+
+sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
