Tidy-up commands

diff --git a/bin/convert-mp4-m4r b/bin/convert-mp4-m4r
--- a/bin/convert-mp4-m4r
+++ b/bin/convert-mp4-m4r
@@ -7,7 +7,7 @@ if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} FILE
 Convert MP3 ausio FILE to ringtome M4R.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: FILE missing")
+	echo "${0##*/}: FILE missing" >&2
 	exit 1
 else
 	for file in "$@"
diff --git a/bin/download-audio b/bin/download-audio
--- a/bin/download-audio
+++ b/bin/download-audio
@@ -8,7 +8,7 @@ if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
 Download a audio or playlist as MP3 from given URL to '$TDIR'.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: URL missing")
+	echo "${0##*/}: URL missing" >&2
 	exit 1
 else
   yt-dlp \
diff --git a/bin/download-file b/bin/download-file
--- a/bin/download-file
+++ b/bin/download-file
@@ -9,7 +9,7 @@ Download a file from given URL to '$TDIR'.
 "
   exit 0
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: URL missing")
+	echo "${0##*/}: URL missing" >&2
 	exit 1
 else
   trap 'exit 130' INT HUP TERM
diff --git a/bin/edit-text b/bin/edit-text
--- a/bin/edit-text
+++ b/bin/edit-text
@@ -7,14 +7,14 @@ if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} [FILE | NAME]
 Edit given FILE or project NAME.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: FILE | NAME missing")
+	echo "${0##*/}: FILE | NAME missing" >&2
 	exit 1
 elif [ -e "$1" ]; then
   code "$1"
 else
-  readonly PROJECT="$(list-projects --top "$1")"
+  PROJECT="$(list-projects --top "$1")"
   if [ "$PROJECT" = "" ]; then
-  	(>&2 echo "${0##*/}: no such project - $1")
+  	echo "${0##*/}: no such project - $1" >&2
   	exit 2
   else
     code "$PROJECT"
