General Cleanup

diff --git a/bin/csv-view b/bin/csv-view
--- a/bin/csv-view
+++ b/bin/csv-view
@@ -2,12 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} <csv_file>
+if [ "$1" = '--help' ]; then echo "Isage: ${0##*/} CSV_FILE
 
-Display given <csv_file>.
+Display given CSV_FILE.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: <csv_file> missing")
+	(>&2 echo "${0##*/}: CSV_FILE missing")
 	exit 1
 else
 	sed 's/,,/, ,/g;s/,,/, ,/g' "$@" | column -s, -t | less -#2 -N -S
diff --git a/bin/man-show b/bin/man-show
--- a/bin/man-show
+++ b/bin/man-show
@@ -2,12 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} <page>
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} PAGE
 
-Open man pages in Preview.app
+Open man pages with PAGE in Preview.app
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: <page> missing")
+	(>&2 echo "${0##*/}: PAGE missing")
 	exit 1
 else
 	for page in "$@"
diff --git a/bin/net-flush b/bin/net-flush
--- a/bin/net-flush
+++ b/bin/net-flush
@@ -2,12 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} <interface>
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} INTERFACE
 
-Flush routes for your <interface> (like en0, en1, ...). (May require password.)
+Flush routes for your INTERFACE (like en0, en1, ...). (May require password.)
 "
 elif [ $# = 0 ]; then
-  (>&2 echo "${0##*/}: name of <interface> missing")
+  (>&2 echo "${0##*/}: name of INTERFACE missing")
   exit 1
 else
   sudo ifconfig "$1" down && sudo route flush && sudo ifconfig "$1" up
diff --git a/bin/net-serve b/bin/net-serve
--- a/bin/net-serve
+++ b/bin/net-serve
@@ -2,12 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} <file_name> [<port>]
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} FILE_NAME [PORT]
 
-Serve <file_name> via HTTP.
+Serve FILE_NAME via HTTP.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: <file_name> missing")
+	(>&2 echo "${0##*/}: FILE_NAME missing")
 	exit 1
 else
 	while true; do
diff --git a/bin/net-whois b/bin/net-whois
--- a/bin/net-whois
+++ b/bin/net-whois
@@ -2,12 +2,12 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} <url>
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} URL
 
-Display WHOIS rrecord about given <url> or domain.
+Display WHOIS rrecord about given URL or domain.
 "
 elif [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: <url> missing")
+	(>&2 echo "${0##*/}: URL missing")
 	exit 1
 else
 	domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
diff --git a/bin/web-download-youtube b/bin/web-download-youtube
--- a/bin/web-download-youtube
+++ b/bin/web-download-youtube
@@ -2,11 +2,11 @@
 
 set -e
 
-if [ "$1" = '--help' ]; then echo "usage: ${0##*/} [options] <uri>
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} [OPTIONS] URL
 
 Download a (YouTube) video.
 
-valid options:
+Options:
  -v | --video   download video to $HOME/Movies (default)
  -a | --audio   download audio to $HOME/Music
 "
@@ -14,7 +14,7 @@ valid options:
 fi
 
 if [ $# = 0 ]; then
-	(>&2 echo "${0##*/}: <uri> missing")
+	(>&2 echo "${0##*/}: URL missing")
 	exit 1
 fi
 
