Tidy up

diff --git a/bin/msg-ask b/bin/msg-ask
--- a/bin/msg-ask
+++ b/bin/msg-ask
@@ -1,7 +1,14 @@
 #! /bin/sh
 
-set -euo pipefail
+set -e
 
-readonly MESSAGE="${1-"Something happend"}"
-readonly TITLE="${2-Notification}"
-osascript -e "tell app \"System Events\" to display dialog \"$MESSAGE\" with title \"$TITLE\"" > /dev/null 2>&1
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} MESSAGE [TITLE]
+
+Request a user action.
+"
+elif [ $# = 0 ]; then
+	(>&2 echo "${0##*/}: MESSAGE missing")
+	exit 1
+else
+  osascript -e "tell app \"System Events\" to display dialog \"$1\" with title \"${2-Notification}\"" > /dev/null 2>&1
+fi
diff --git a/bin/msg-show b/bin/msg-show
--- a/bin/msg-show
+++ b/bin/msg-show
@@ -1,7 +1,14 @@
 #! /bin/sh
 
-set -euo pipefail
+set -e
 
-readonly MESSAGE="${1-"Something happend"}"
-readonly TITLE="${2-Notification}"
-terminal-notifier -message "$MESSAGE" -title "$TITLE" -ignoreDnD
+if [ "$1" = '--help' ]; then echo "Usage: ${0##*/} MESSAGE [TITLE]
+
+Display a notification message.
+"
+elif [ $# = 0 ]; then
+	(>&2 echo "${0##*/}: MESSAGE missing")
+	exit 1
+else
+  terminal-notifier -message "$1" -title "${2-Notification}" -ignoreDnD
+fi
